name: Build and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: build exe
    runs-on: Windows-2019
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: build app
      run: dotnet build .\Terminal.sln --configuration Release --no-restore
    - uses: actions/upload-artifact@v3
      with:
          name: build
          path: Terminal/bin/Release/MQLibrary.exe
    - name: version
      id: tag_name
      run: |
        echo "version=v$(get-date -Format "yy.MM.dd.hh")" >> $env:GITHUB_OUTPUT
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: Terminal/bin/Release/MQLibrary.exe
        tag_name: ${{ steps.tag_name.outputs.version }}
        
        
       
