name: build a .NET app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: Windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: build app
      run: dotnet build Terminal.sln      
    - name: Tag the repository
      id: tag
      run: |
        TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
        echo "$TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
        git push origin $TAG
    - name: create release
      uses: softprops/action-gh-release@v1
      with:
        files: Terminal/bin/Debug/MQLibrary.exe
        tag_name: ${{ steps.tag.outputs.tag }}
        
        
       
